CREATE DATABASE IF NOT EXISTS testdb;

USE testdb;

CREATE TABLE CUSTOMER (ID varchar(255),CUSTOMER_NAME varchar(255),PHONE_NUMBER varchar(255),EMAIL varchar(255));

CREATE TABLE SUBSCRIPTION (ID varchar(255),CUSTOMER_ID varchar(255),CREATED_DATE DATE, END_DATE DATE, DURATION NUMERIC, DURATION_UNITS varchar(255),BILLING_FREQUENCY varchar(255),BILLING_FREQUENCY_UNITS varchar(255),PRICE NUMERIC,CURRENCY varchar(255),PRODUCT_CODE varchar(255),NEXT_BILL_DATE DATE)